### ISSUE TITLE
Problems with keyboard and touchpad

### ISSUE THREAD

**Issue by marcorivm** [connorkuehl/connorkuehl.github.io#1]
Hi man, saw your guide for installing ubuntu on a dell inspiron 7559, I just installed ubuntu a few days ago but i'm struggling with the touchpad, sometimes when clicking it moves to the lower left corner and clicks the trashcan, I'm also having issues with the keyboard, when writing sometimes keypresses do not get registered or the cursor moves around the text. I was wondering if you experienced any issues?

**Comment by connorkuehl** [comment]
Hi, @marcorivm 

I also experienced that issue with the touchpad. I think it's just a quirky touchpad driver. I just dealt with it by being really careful. When you go to click make sure you only click with one finger or click by tapping the touchpad. I think it's just overly sensitive because it's "listening" for gestures like scrolling and when you click, the downward force could possibly be detected as a drag. 

I haven't experienced the same keyboard issue you're having through. Maybe some setting was accidentally activated in the Keyboard Preferences or Accessibility menus? Hope that helps.
