### ISSUE TITLE
Clarification about Nvidia Driver

### ISSUE THREAD

**Issue by techopswhiz** [connorkuehl/connorkuehl.github.io#2]
Is it necessary to install the nvidia driver? If not, won't it just use the Intel, or would it power the nvidia doing nothing or something? Would just adding nomodeset to the grub config be bad? Although, my second monitor appears not to be working at the moment, without changing any graphics settings.

I also have secure boot on still, and would like to keep it that way if possible... Although I'm not sure what the point is.

**Comment by connorkuehl** [comment]
It's not necessary to install the Nvidia driver, but if you don't, the
system will use nouveau which will use the dedicated video card 100% of the
time which results in shorter battery times. So no, it won't use Intel by
default. The Nvidia driver provides Nvidia prime which lets you choose the
Intel GPU for better battery life.

Adding nomodeset is not ideal. I think it is limiting. I'd need to read up
on it more, but it might defer rendering to software instead of your
hardware (your video card)

I don't remember any stipulations about secure boot, but if you're dual
booting with Windows it might cause issues.

**Comment by techopswhiz** [comment]
Any issues relating to windows in particular seem to have expired, at least, I'm not having any issues with that, both boot fine and drives behave. The only thing I'm running into here is that you can't install third-party packages on Ubuntu if secure boot is enabled. I think that includes nouveau, definitely includes nvidia. I don't plan to need anything graphic intensive on Linux... Is there a way to get the intel driver to work without an nvidia driver set to stay off?

**Comment by connorkuehl** [comment]
If there is, there's no way that I'm aware of.

**Comment by techopswhiz** [comment]
Disabled secure boot, install nvidia-381, rebooted without changing anything. appears to have worked, so far...

**Comment by techopswhiz** [comment]
`sudo prime-select intel` then reboot, freezes.  Then I add `acpi_osi=` to the quiet splash line, leaving out the backlight thing, and it boots, and backlight controls work fine...

**Comment by techopswhiz** [comment]
Just curious - what does this part accomplish?

> Open /etc/modprobe.d/bumblebee.conf in your favorite text editor.

> Append blacklist entries to match the Nvidia driver you installed to the bottom of this file.
> blacklist nvidia-367
> blacklist nvidia-367-updates
> blacklist nvidia-experimental-367

**Comment by connorkuehl** [comment]
It should stop the Nvidia driver from loading while the system is booting to prevent the GPU being turned on and used automatically afaik.

**Comment by techopswhiz** [comment]
Okay - I skipped it, appears to behave.
